
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import AztecGateway7683ContractArtifactJson from './aztec_gateway_7683-AztecGateway7683.json' assert { type: 'json' };
export const AztecGateway7683ContractArtifact = loadContractArtifact(AztecGateway7683ContractArtifactJson as NoirCompiledContract);


      export type Filled = {
        order_id: (bigint | number)[]
origin_data: (bigint | number)[]
filler_data: (bigint | number)[]
      }
    

/**
 * Type-safe interface for contract AztecGateway7683;
 */
export class AztecGateway7683Contract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, AztecGateway7683ContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, AztecGateway7683Contract.artifact, wallet) as Promise<AztecGateway7683Contract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, portal: EthAddressLike) {
    return new DeployMethod<AztecGateway7683Contract>(PublicKeys.default(), wallet, AztecGateway7683ContractArtifact, AztecGateway7683Contract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, portal: EthAddressLike) {
    return new DeployMethod<AztecGateway7683Contract>(publicKeys, wallet, AztecGateway7683ContractArtifact, AztecGateway7683Contract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof AztecGateway7683Contract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<AztecGateway7683Contract['methods'][M]>
  ) {
    return new DeployMethod<AztecGateway7683Contract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      AztecGateway7683ContractArtifact,
      AztecGateway7683Contract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return AztecGateway7683ContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(AztecGateway7683ContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'config' | 'claimable_orders' | 'open_orders' | 'order_status' | 'used_nonces' | 'order_filler_data'> {
      return {
        config: {
      slot: new Fr(1n),
    },
claimable_orders: {
      slot: new Fr(3n),
    },
open_orders: {
      slot: new Fr(4n),
    },
order_status: {
      slot: new Fr(5n),
    },
used_nonces: {
      slot: new Fr(6n),
    },
order_filler_data: {
      slot: new Fr(7n),
    }
      } as ContractStorageLayout<'config' | 'claimable_orders' | 'open_orders' | 'order_status' | 'used_nonces' | 'order_filler_data'>;
    }
    

  public static get notes(): ContractNotes<'UintNote'> {
    return {
      UintNote: {
          id: new NoteSelector(0),
        }
    } as ContractNotes<'UintNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** claim_private(secret: array, order_id_bytes: array, origin_data_bytes: array, filler_data_bytes: array) */
    claim_private: ((secret: (bigint | number)[], order_id_bytes: (bigint | number)[], origin_data_bytes: (bigint | number)[], filler_data_bytes: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(portal: struct) */
    constructor: ((portal: EthAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** fill(order_id_bytes: array, origin_data_bytes: array, filler_data_bytes: array) */
    fill: ((order_id_bytes: (bigint | number)[], origin_data_bytes: (bigint | number)[], filler_data_bytes: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** fill_private(order_id_bytes: array, origin_data_bytes: array, filler_data_bytes: array) */
    fill_private: ((order_id_bytes: (bigint | number)[], origin_data_bytes: (bigint | number)[], filler_data_bytes: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config() */
    get_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config_private() */
    get_config_private: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_order_filler_data(order_id_bytes: array) */
    get_order_filler_data: ((order_id_bytes: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_order_status(order_id_bytes: array) */
    get_order_status: ((order_id_bytes: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** open(order: struct) */
    open: ((order: { fill_deadline: (bigint | number), order_data_type: (bigint | number)[], order_data: (bigint | number)[] }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** open_private(order: struct) */
    open_private: ((order: { fill_deadline: (bigint | number), order_data_type: (bigint | number)[], order_data: (bigint | number)[] }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_log(log_ciphertext: struct, tx_hash: field, unique_note_hashes_in_tx: struct, first_nullifier_in_tx: field, recipient: struct) */
    process_log: ((log_ciphertext: { storage: FieldLike[], len: (bigint | number) }, tx_hash: FieldLike, unique_note_hashes_in_tx: { storage: FieldLike[], len: (bigint | number) }, first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { Filled: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      Filled: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "order_id",
            "type": {
                "kind": "array",
                "length": 32,
                "type": {
                    "kind": "integer",
                    "sign": "unsigned",
                    "width": 8
                }
            }
        },
        {
            "name": "origin_data",
            "type": {
                "kind": "array",
                "length": 300,
                "type": {
                    "kind": "integer",
                    "sign": "unsigned",
                    "width": 8
                }
            }
        },
        {
            "name": "filler_data",
            "type": {
                "kind": "array",
                "length": 32,
                "type": {
                    "kind": "integer",
                    "sign": "unsigned",
                    "width": 8
                }
            }
        }
    ],
    "path": "AztecGateway7683::Filled"
},
        eventSelector: EventSelector.fromString("0x8791995f"),
        fieldNames: ["order_id","origin_data","filler_data"],
      }
    };
  }
  
}
