[package]
name = "aztec_gateway_7683"
type = "contract"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.87.2", directory = "noir-projects/aztec-nr/aztec" }
token = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.87.2", directory = "noir-projects/noir-contracts/contracts/app/token_contract" }
