[package]
name = "aztec_gateway_7683"
type = "contract"
authors = ["Substance Labs"]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.1.3", directory = "noir-projects/aztec-nr/aztec" }
token = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.1.3", directory = "noir-projects/noir-contracts/contracts/app/token_contract" }
